config/routes.rb
Rails.application.routes.draw do
  devise_for :employees, controllers: {
    :sessions => "employees/sessions",
    :passwords => "employees/passwords",
    :registrations => "employees/registrations" } 
  root to: "pages#index"
  get '/contact', to: 'pages#contact'
  resources :employee
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
  
  # VALID_DOB_REGEX = /(^(((0[1-9]|1[0-9]|2[0-8])[\/](0[1-9]|1[012]))|((29|30|31)[\/](0[13578]|1[02]))|((29|30)[\/](0[4,6,9]|11)))[\/](19|[2-9][0-9])\d\d$)|(^29[\/]02[\/](19|[2-9][0-9])(00|04|08|12|16|20|24|28|32|36|40|44|48|52|56|60|64|68|72|76|80|84|88|92|96)$)/
  # validates :DOB, format: { with: VALID_DOB_REGEX }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
        
end

app/controllers/Employees/confirmations_controller.rb
# frozen_string_literal: true

class Employees::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/Employees/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Employees::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/Employees/passwords_controller.rb
# frozen_string_literal: true

class Employees::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/Employees/registrations_controller.rb
# frozen_string_literal: true

class Employees::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   @employee = Employee.new(configure_permitted_parameters)
  #   if @employee.save
  #     flash[:success] = "Employee Onboarded!!"
  #     redirect_to employee_path(current_employee.id)
  #   else
  #     render 'new'
  #   end
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute, :name, :email, :password, :password_confirmation, :DOB])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute, :name, :email, :password, :password_confirmation, :DOB])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   new_user_session_path
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/Employees/sessions_controller.rb
# frozen_string_literal: true

class Employees::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/Employees/unlocks_controller.rb
# frozen_string_literal: true

class Employees::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation, :contact, :designation)}
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :password_confirmation, :contact, :designation)}
  end

  def after_sign_in_path_for(resource)
    employee_path(current_employee.id)
  end
end

app/controllers/employee_controller.rb
class EmployeeController < ApplicationController

  # before_action :save_password, only: [:create]
    
    def show
      @employee = Employee.find(params[:id])
    end

    def index
      @employees=Employee.all
    end

    def create
      @employee = Employee.new(employee_params)
      if @employee.save
        flash[:notice] = "New Employee Onboarded!"
        OnboardMailerJob.perform_later employee_params
        redirect_to employee_path(current_employee.id)
      else
        render 'new'
      end
    end

    private

      def employee_params
        params.require(:employee).permit(:name, :email, :password, :password_confirmation, :contact, :designation)
      end

      def save_password
        @temp_password = employee_params[:password]
      end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
  
  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employee_helper.rb
module EmployeeHelper
  def gravatar_for(employee)
    gravatar_id = Digest::MD5::hexdigest(employee.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: employee.name, class: "gravatar")
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/employee/index.html.erb
<div class="list">
  <% @employees.each do |employee| %>
  <%= employee.name %><br />
  <%= employee.email %><br />
  <%= employee.designation %><br /><br />
<% end %>
</div>

app/views/employee/new.html.erb
<%= provide(:title, 'Onboarding') %>
<h1>Employee Onboard</h1>
<div class = "form-box">
  <div class = "details">
    <%= form_for Employee.new, url: {action: "create"} do |form| %>
      <div class = "field">
        <%= form.label :name %><br />
        <%= form.text_field :name %>
      </div>
      <div class="field">
        <%= form.label :email %><br />
        <%= form.text_field :email %>
      </div>
      <div class="field">
        <%= form.label :designation %><br />
        <%= form.text_field :designation %>
      </div>
      <div class= "field">
        <%= form.label :contact %><br />
        <%= form.text_field :contact %>
      </div><br />
      <div class="field">
        <%= form.label :password %><br />
        <%= form.password_field :password %>
      </div>
      <div class="field">
        <%= form.label :password_confirmation %><br />
        <%= form.password_field :password_confirmation %>
      </div>
      <%= form.submit "Onboard", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/employee/show.html.erb
<% provide(:title, "Profile") %>
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "LOCONAV", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li class="item" ><%= link_to "Employees", employee_index_path %></li>
        <li class="item" ><%= link_to "Onboard", new_employee_path %></li>
        <li class="item" ><%= link_to "Project", "#" %></li>
        <li class="dropdown abc" >
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" 
          aria-expanded="false">Account<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Edit", edit_employee_registration_path %></li>
            <li><%= link_to "Sign Out", destroy_employee_session_path, method: :delete %></li>
          </ul>
        </li>        
      </ul>
    </nav>
  </div>
</header>

<div class ="container left">
  <div class="row">
    <aside>
      <section class="user_info">
        <h1>
          <%= gravatar_for @employee %><br /><br /><br /><br /><br />
          <%= @employee.email %>
        </h1>
      </section>
    </aside>
  </div>
</div>
<div class="container right">
  <div class = "profile">
    <p>Name:<%= @employee.name %></p><br />
    <p>Email:<%= @employee.email %></p><br />
    <p>Date Of Birth:<%= @employee.DOB %></p><br />
    <p>Contact Number<%= @employee.contact %></p><br />
    <p>Designation:<%= @employee.designation %></p>
  </div>
</div>

app/views/employees/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/employees/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_employee_registration_path%><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Employee_Portal | <%= yield(:title) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Raleway" />
  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "LOCONAV", root_path, id: "logo" %>
      </div>
    </header>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/contact.html.erb
<div class="form-box">
  <div class="details">
    <h3>Contact Information</h3>
    <p class="contact-icons">
      <!-- insert images of small icons here -->
      "+91 8448440771"
    </p>
    <p>
      For Business Enquiry<br />
      hi@loconav.com
    </p>
    <p>
      For Support<br />
      support@loconav.com
    </p>
    <p>
      Global Office Address<br />
      355 Bryant Street, Suite 403,
      San Francisco, CA 94107
       <br />
      B-13/14, LocoNav ThinkValley, Sector 32,
      Gurugram, Haryana 122003
    </p>
  </div>
</div>

app/views/pages/index.html.erb
<% provide(:title, "Home") %>
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "LOCONAV", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown abc" >
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Our Services<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "abc", '#' %></li>
            <li><%= link_to "def", '#' %></li>
            <li><%= link_to "ghi", '#' %></li>
          </ul>
        </li>
        <li class="abc" ><%= link_to "Contact", contact_path %></li>
      </ul>
    </nav>
  </div>
</header>
<p class="heading">Welcome to the Employee login Portal</p>
<%= link_to 'Lets Go', new_employee_session_path, :class=> "btn btn-info" %>